### ISSUE TITLE
There are no samples

### ISSUE THREAD

**Issue by skakri** [KhronosGroup/Vulkan-Samples-Deprecated#1] opened 2016-02-16 20:41 UTC
Vulkan 1.0 documentation has been released but this repo is still empty. Why so?

**Comment by oddhack** [comment] 2016-02-16 21:03
This repository is for samples contributed by member companies (and possibly others). There are a couple in flight, but the companies are doing some checks with their legal departments regarding copyrights and licenses. As they sort through that process, some samples should start to populate the repo.

I believe there are also some sample programs in the LunarG Vulkan SDK.

**Comment by HaydnTrigg** [comment] 2016-03-10 12:08
There is still a complete lack of samples here.

**Comment by mre4ce** [comment] 2016-03-11 17:31
It has taken a little longer than expected to sort out the CLA process. We should get this resolved very soon, at which point we will start to populate this repository. For the time being, I recommend checking out the Vulkan resources page which has references to various demos, tutorials and samples.

https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md

**Comment by sp82** [comment] 2016-04-28 11:31
"There is still a complete lack of samples here." +1

I think you don't need to put here complex samples with license issues. 
Like the "Khronos Vulkan Conformance Tests", will be very usefull to have official set of examples that shows how to use the commands described in the specs.
An official starting point for everyone looking for code.

**Comment by mre4ce** [comment] 2016-04-28 20:35
The problem is not that we have complex samples that need special licensing. We went through the process of unifying the licensing as much as possible across all Khronos repositories, including setting up the CLA assistant, to make it easier for everyone to contribute. Unfortunately these things take time.

If you are looking for samples that build up a Vulkan app step by step, then I recommend having a look at the https://github.com/LunarG/VulkanSamples repository which is also listed at https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/vulkan/resources.md

**Comment by HaydnTrigg** [comment] 2016-04-29 06:24
Why can't the examples just be released with an existing easy to use licence like any other repository? Such as the Apache 2.0 license that LunarG is using.

This issue was opened since Feb 17th, if this is a holdup on licencing then perhaps that's typical that all we can expect is another delay after delay as with the release of the API. If you need a license, get a lawyer to draft one up it seriously doesn't take this long to sort out the license for publicly available examples especially when there is an abundance of them already used by everyone else (LunarG has the right idea).

**Comment by mre4ce** [comment] 2016-04-29 16:45
Unfortunately it wasn't quite that simple. Even though the end result may be very similar, we had to make sure that the licensing works for all Khronos member companies. My apologies for any inconvenience this has caused.

**Comment by Cleroth** [comment] 2016-04-29 16:51
My worry is for the possibility of issues like these emerging more frequetly in other areas too, as we start to see more and more delays with Vulkan. It doesn't look good for a graphics API that is being built around becoming the new standard.

**Comment by mre4ce** [comment] 2016-05-25 19:56
The repository has been populated with a first set of samples.

**Closed as completed by mre4ce** 2016-05-25 19:56 UTC
